apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-lgtm-config
  namespace: observability
data:
  lgtm-config.yaml: |
    server:
      http_listen_port: 3000
    analytics:
      reporting_enabled: false
    common:
      path_prefix: /var/lgtm
