---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-release
  namespace: metallb-system
spec:
  interval: 5m
  path: "./homelab/core/metallb/release"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-config
  namespace: metallb-system
spec:
  dependsOn:
    - name: metallb-release
  interval: 5m
  path: "./homelab/core/metallb/config"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
