{
 "title": "New dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "node", "query": { "query": "label_values(host_name)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Global CPU Utilization",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(system_cpu_utilization_ratio{state=~\"user|system|nice|softirq|steal|irq|wait\"})\n/ count(system_cpu_utilization_ratio{state=\"idle\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(k8s_pod_cpu_request_utilization_ratio)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(k8s_pod_cpu_limit_utilization_ratio)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Global RAM Utilization",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(system_memory_usage_bytes{state=\"used\"}) \n/ sum(system_memory_usage_bytes)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(k8s_pod_memory_request_utilization_ratio)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(k8s_pod_memory_limit_utilization_ratio)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(k8s_node_uptime_seconds_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Networking",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(k8s_node_network_io_bytes_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (k8s_namespace_name) (k8s_pod_uptime_seconds_total))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(system_cpu_utilization_ratio{state=~\"user|system|nice|softirq|steal|irq|wait\"})\n  / count(system_cpu_utilization_ratio{state=\"idle\"})\n) * sum(system_cpu_logical_count)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(k8s_pod_cpu_request_utilization_ratio) * sum(system_cpu_logical_count)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(k8s_pod_cpu_limit_utilization_ratio) * sum(system_cpu_logical_count)",
     "legendFormat": "__auto"
    },
    { "expr": "sum(system_cpu_logical_count)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(system_memory_usage_bytes{state=\"used\"}) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(k8s_pod_memory_request_utilization_ratio)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(k8s_pod_memory_limit_utilization_ratio)",
     "legendFormat": "__auto"
    },
    { "expr": "sum(system_memory_usage_bytes)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Running Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by (k8s_namespace_name) (k8s_pod_uptime_seconds_total))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(system_cpu_utilization_ratio{state=~\"user|system|nice|softirq|steal|irq|wait\"})\n/ count(system_cpu_utilization_ratio{state=\"idle\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster RAM Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(system_memory_usage_bytes{state=\"used\"}) \n/ sum(system_memory_usage_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (k8s_namespace_name) (k8s_pod_cpu_utilization_ratio)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Utilization by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(k8s_namespace_name) (k8s_pod_memory_usage_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Node - jupiter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(system_cpu_utilization_ratio{host_name=\"$node\", state=~\"user|system|nice|softirq|steal|irq|wait\"})\n/ count(system_cpu_utilization_ratio{host_name=\"$node\", state=\"idle\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_usage_bytes{host_name=\"$node\", state=\"used\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(system_memory_usage_bytes{host_name=\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods on node",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(k8s_pod_uptime_seconds_total{host_name=\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 11, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "k8s_pod_uptime_seconds_total{host_name=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk space",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_filesystem_usage_bytes{host_name=\"$node\", state=\"free\", mountpoint=\"/\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(system_filesystem_usage_bytes{host_name=\"$node\", state=~\"used|reserved\", mountpoint=\"/\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k8s_node_uptime_seconds_total{host_name=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}