apiVersion: v1
kind: Secret
metadata:
    name: open-webui
    namespace: ollama
type: Opaque
stringData:
    OLLAMA_API_KEY: ENC[AES256_GCM,data:acm6so8rUfJxhYmikrO+0NuK2G80Nu7Zi1LR3WCdDlMqGFwotteT52tSzTw4w3uFBFVs99P/0D6N,iv:yjKvwS9t8WKILCSeDBrwJ37BugDd25GmfcWcbKo0rB4=,tag:A8o2Oe58DAvy9qWbCWprtg==,type:str]
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:RNcFWKJMWQRBNaKNOx0lc53BJlWbyYQmYPICE7OK5LrqiMBxtQOcX/5rSaK+IPAv3youTwI8kwp9SBOAfIQL1g==,iv:E9KVok1kV7vA0Y6QG74hmNv0zpJ/hbqZAuQP2SHUNyU=,tag:Lz/iODtjvX5j6NnT+b+JPQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jmtzxhr8gr37jt4uw9h49v6m5wtyxv56lev5rvju0knuvfk57e5sfwdm77
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZXJvQlJ1NzFVNWVLWVBu
            SEVzd3ZDOXpjcERIZi8wWkd0UE1CcEhucERVCnIxVjdhM1VicFVlaWZ6QXc3NzY4
            RE9zZWpUZTByMGlLWEVjcmczcUNyVDQKLS0tIFlMSXFFaXJMbHN2QUVBQmJWaHkr
            dTREZFYxZTZScGNVNzF2TlB2QkVIQnMKr0zlR/EyWRTzMePNgh+J6A67j8Ya25rX
            +m+q+eaVGlphIoePTjv/PN+6I7Zi/FUUw+Em/wQnG+pcEz6HmPNW0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-10T11:03:14Z"
    mac: ENC[AES256_GCM,data:x6gIm4okAG3+2vOiniafAF/iDVs1UwjYHK0mMeEJQNicQ73du43Q6JCuyTd8OIXJXeaggDxdxRx+X0AG/H6fMojJsM1MFFGu8UIZzCoZAxRPsbTkRtEa6JtapoaBpZjdZWXmWTIRYGYNB5rYQgMFirL+R0YgNjxT4CyBtTeGbjU=,iv:0JfIITk518GC05L+LfKylsyER908SIdxj8UYuOIgmlA=,tag:9KUvxtnrI1194QAxiAi8wA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
