---
apiVersion: v1
kind: Namespace
metadata:
  name: openebs
  labels:
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openebs-release
  namespace: openebs
spec:
  interval: 5m
  path: "./homelab/core/storage/release"
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-repo
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openebs-config
  namespace: openebs
spec:
  dependsOn:
    - name: observability-release
  interval: 5m
  path: "./homelab/core/storage/config"
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-repo
    namespace: flux-system
