---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-lgtm
  namespace: monitoring
  labels:
    app: otel-lgtm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-lgtm
  template:
    metadata:
      labels:
        app: otel-lgtm
    spec:
      containers:
      - name: otel-lgtm
        image: grafana/otel-lgtm:latest  # ✅ Official LGTM image
        ports:
          - containerPort: 3000   # Grafana UI
          - containerPort: 3100   # Loki
          - containerPort: 4317   # OTel gRPC
          - containerPort: 4318   # OTel HTTP
          - containerPort: 14268  # Tempo
        volumeMounts:
          - name: config-volume
            mountPath: /etc/lgtm-config.yaml
            subPath: lgtm-config.yaml
      volumes:
        - name: config-volume
          configMap:
            name: otel-lgtm-config
