apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden
    namespace: vaultwarden
type: Opaque
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:1lqRfTsmN3eltr7q2iGAD60pt7Cvegxtk0Kq/VrCctewlDr6/NZJZCT3jiSjfpaVCmmvfegAT3LF6levd2+zcw==,iv:glkNutdL9UAm8ApGKr9KV8unor29Gu28uM6yOtDrSVc=,tag:/YIK+AONnTinxuNgHeqJnA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcmtnVGtkdTRIN2IyUm9s
            VEdpazdSNW9XaFFMck9EdzRwcU9TbmZ2SGhzCm5ZeEU1a0g2QVZIRmVTRW5VeXEx
            enZNNDVyd05xTkN5Y05kMWlVTTIxeFUKLS0tIFU2blhrWVhhRkt5VGZ3Qy9DZTZC
            MmxtZ21RNkNvZmgyVnd6OG50TU95NDAKo/HDgMOJHUwQ9DTevBY7OlvtqOjl5tk4
            L1KnG1UT+D0ff0yzvGTHj0wN+rVpA7GPphH51PuvcDQZVwfshjkzAw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jmtzxhr8gr37jt4uw9h49v6m5wtyxv56lev5rvju0knuvfk57e5sfwdm77
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-20T11:33:35Z"
    mac: ENC[AES256_GCM,data:sraCJ5b5L5OhEidyBzxSHOXyZYqXa4pBUWPT02MXvH8ooeulJlppWzFmdLYFRtCRf0qwcRDQHzYa09EpAkg9oKJVcKVnnJgdVD6/HRFyRkit3q47WQzuq994KoIJajWLjfajMniqSt+SM23GrzKLDqowhZbWSg1ndX3d9JmDQJ8=,iv:u1inOF0deGvqZI9OFCVlkOb8mzs2nZpdd0VzPuRwKWE=,tag:RmSsTkM+KJop9qFR+xflpg==,type:str]
    version: 3.13.3
