---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flux-metrics
  namespace: observability
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: flux
  namespaceSelector:
    matchNames:
      - flux-system
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 30s
