---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: fluxcd
  namespace: flux-system
spec:
  interval: 1h
  url: https://fluxcd-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: flux2
      sourceRef:
        kind: HelmRepository
        name: fluxcd
        namespace: flux-system
      version: "2.4.0"
  install:
    createNamespace: true
  values:
    prometheus:
      enabled: true
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flux-metrics
  namespace: observability
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: flux
  namespaceSelector:
    matchNames:
      - flux-system
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 30s
