---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gitrepository.yaml
  - flux-kustomization.yaml
  - https://github.com/fluxcd/flux2/releases/download/v2.4.0/install.yaml
