apiVersion: ENC[AES256_GCM,data:bNQ=,iv:W4IJSdfhwVSVjeRXQiQUOYcu5TdsOo48cfNFQniqHuw=,tag:6Di3HXMBDuo+3qbmPXKe6g==,type:str]
kind: ENC[AES256_GCM,data:DhBFLbu6,iv:hg5mrF93kEioD9jV7pYPKBayvB0bXh6Gg1iBgw0/Q2w=,tag:bT8wVTs6dxn/Gv8L5TyFOA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:srL5HlcRVikCS+pfd+anIcLkSmTRzF0gsQ==,iv:xL+fvmgE5a7YmXzKLiYHxaPlCG4oDpHrkKVB8OUipWM=,tag:Y6Srevt2gzRL+0eEGnPbWw==,type:str]
    namespace: ENC[AES256_GCM,data:R0rTuwNeSXwJGyiK,iv:Cw/+JUVwhxi+DS3ZLtq5lgQESx8nbfUb5lck96YGi3U=,tag:YeaRqBwqWKnlB/JCNYeZlg==,type:str]
type: ENC[AES256_GCM,data:p7Oiqe1t,iv:+5DInV5qAFycXeCwZFVBY04OlTjkyEE+rqFj8kzy4Ik=,tag:d4gFCW+ttj/dys153QtE+Q==,type:str]
data:
    token: ENC[AES256_GCM,data:42Okoc3RqkbeE/QLv1Wwqj/p3Q7MxPj4vxFUoKwpX28HsAgGZb65pA==,iv:mVZD1orPwJaop8yTxfyO4ErCbFCN5CpCPSIlZpJaiM8=,tag:shCqKy8Nddgc+y9z7LAEvw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jmtzxhr8gr37jt4uw9h49v6m5wtyxv56lev5rvju0knuvfk57e5sfwdm77
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYTA2aWlqbUhMdTc4SCtz
            MVJncUNQNnl3OW5TbjgwUThSMzZZVW4zd2w4CjF1M0xFM1VOV3M5NWRqays3MnZD
            MDZaMGZIK3RYODJCRVMxWEJScEpEYjQKLS0tIGx4V3pXam5YdS9hS0dleUNDTjJZ
            eFRPQmkzbERpa3VtUDRtRThFQlpkRWcKbzvkvl21qTdOLwcTjLcXrGuGr4bNtl14
            dlqJbb1l/EZfimACtB4DWirLZefUsi3Mpcd3XHDY8ZB8RQeH5g00yA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-19T16:03:25Z"
    mac: ENC[AES256_GCM,data:tJ5JZj391YVaYAwLqyQerGvOEyUIPdwQ5/46+Dz6JSppVLP8WJrSpl+c+4PrttTGZXx3i3ST+AqESR3ZFH8D34CtOpUrbwC1/mJD3i+zQWI3dn7fBUIsxWukk8G3pGae0z/Uohg/TmEHtW5WLHPfSgPxvYIlTpNYg5EOvrlaUbc=,iv:kfgWQZUuH9ZsMdaE9Wkvg/Z1Ey2cztKArpitJFTUYLs=,tag:j5ewIWHboO2wYb5Ait0g3w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
