apiVersion: ENC[AES256_GCM,data:1TY=,iv:0qokmMok537Wcwb1JIuc/5VkhleoNkJR5J22NO2AoZI=,tag:iu8fPBe4bP+K60MnuIp9EQ==,type:str]
kind: ENC[AES256_GCM,data:mgWPMzRs,iv:2zRW6r07nlG8uQhNrfhWTuxItBLwa4BFKwoaLqpbZow=,tag:KRwuSED7yuj3iYWGRfyuew==,type:str]
metadata:
    name: ENC[AES256_GCM,data:vSFm+UrVMass7+n9yR7VvYp/HuIvCUv3Zg==,iv:M/+hVeEpdHh6866UovBEKcooG3cjTEQ5dl162J9z+Sg=,tag:7Oyp9tTgLt8/TN2R/91iGA==,type:str]
    namespace: ENC[AES256_GCM,data:IVldEIj6VD3ef1bf,iv:WjvY7MbME6f1LnxSBuF3+WQL6VJdKhOdXS1SpVs3wtY=,tag:Z2wAp36vu3IPHaVJyMJRMQ==,type:str]
type: ENC[AES256_GCM,data:edyF2oDi,iv:DKwYOdIqVY2EaKxwcisEqfazocweLna8mJTf0pUB1tk=,tag:ksyqz1PVXN2olVc5rnN1yQ==,type:str]
data:
    token: ENC[AES256_GCM,data:hJlFdi1xQ+64IZc3aF/JUwCT9U7iJq36lXz2882qpMrUWzTQzShE9A==,iv:QMj8MryM7HDf+xYmILt5MTAq/uL6pfaJVkC+wJFAUPM=,tag:yZ8G0F/U7HyA1Em48bxq+A==,type:str]
sops:
    age:
        - recipient: age1jmtzxhr8gr37jt4uw9h49v6m5wtyxv56lev5rvju0knuvfk57e5sfwdm77
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPWWRLdUUwUDBTck5IRkF0
            MTVIZzRaSXFEZzBvSmxlSndlc3pycjhGSVZzCkdwNGR4UVRTOVNZSFVmU0Z2YlZZ
            bnkzZHR3NDFMb1ZpNXo2V3N5MUxzSnMKLS0tIFU1dHAySllDdzF5RGdQK25yc1Yv
            RGMyS2ZTQUhWR2hqVExPaVdLSzIzc00Kj2U9YxUEV+dSSPXT3I7VrHu/keubmard
            2gpQ7QOOvky1GHDNH7xAP4v8y8ZcIgb+k2I33YD3FMmNOtj7Fod6sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-18T22:58:46Z"
    mac: ENC[AES256_GCM,data:QQ+HsUulYORyF3wH69Tj62HDWdJW34Liq5vSmE7UcSqzUcAtjK3Uxf0o8rzI+7nkUlTW8P74y78b5nms8e5nRkWynarghy9/T8f6GyhbsCv4QXaIoe1WYrIfTMOL99FUkzriwL7G+GCrxjbN7MQUNnAFSGZk7y2IachglVyelwc=,iv:BOnbSK7uMse/gR/QfOcoFhlZUI+ScR+0/MDFHAUr4kk=,tag:H65U+PfzH9KbM7inl+Qd8Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
