---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 10m0s
  url: https://kubernetes-sigs.github.io/external-dns
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  interval: 10m0s
  targetNamespace: external-dns
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: external-dns
  values:
    policy: sync
    txtOwnerId: hmlb
    sources:
      - gateway-httproute
      - service
    provider: cloudflare
    extraArgs:
      #- --label-filter=external-dns==true
      - --managed-record-types=A
      - --managed-record-types=AAAA
    env:
      - name: CF_API_TOKEN
        value: file:/cloudflare/token
    secretConfiguration:
      enabled: true
      mountPath: /cloudflare
