apiVersion: ENC[AES256_GCM,data:oac=,iv:Y43dV8TjCpzUQbh72U2N556ijKj4DwOfRC725K1y1hU=,tag:BIOKNK4TNf3ZI2VCCux1Qg==,type:str]
kind: ENC[AES256_GCM,data:UsH7OrQh,iv:Vjbfa21KvV6WvUObfu4FdpQ3EAdTnDLu5sd2WVn8et4=,tag:xyZF4j1uWtk7u611/aWkxg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:NF5y0KCxVluJ0CDGg/cqkA==,iv:rj9omqvlOhbpzngmd56kPl7qaFy4WLLaYzG5HOLf4H0=,tag:fZX7ZhH9HlBnNi9n8somAw==,type:str]
    namespace: ENC[AES256_GCM,data:p4otiOxVmE3HrwhX,iv:8i5mvNtzTdyyfybLWgcHcztQxNkRIwkJ0KKMjGIL6PQ=,tag:iiceXcjeQ+nt7IjcHqm0uQ==,type:str]
stringData:
    token: ENC[AES256_GCM,data:30zWgCmIgucuqaQUJaVdIzRThe99IGe3mfmAVNbfSSP5t9YWGM1oKQ==,iv:88BkfpTbZ8Bu6WLJ0lNKeR0UYudehwjfljypqj8lPwo=,tag:b6BGWD4mXODHrQ4iqVrJ6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jmtzxhr8gr37jt4uw9h49v6m5wtyxv56lev5rvju0knuvfk57e5sfwdm77
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyL2kwVkFPODQxN1BiUFJZ
            QWlndG05NmJINnBpMkwwenhkdXhLWHNpVUZnCnhoQkFkcDZvSkRnMzdaa3VSVGpC
            RlRKaHJ4dTMzc2pPL21lejhXSzYrOTQKLS0tIE96RnQyYUNRRi9La3pYcDVzZW42
            ODVIdE9KTlRBZUxHL0J3aU5HK3FCOTAKQvNKCMTeQKqv3e78wupW9WxdRKU7bSe+
            TADXtokn246p0YLi5CaBTztbD6NH9MQAMu8EknEdtEmywWTIWFd8iA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-24T13:59:38Z"
    mac: ENC[AES256_GCM,data:IwpxAfPoG0lOB8kneC2vxHZ9kvGQ0TBAE4lyl3poazPT2/ufL10mGPNraaa+9pYOkrdBFgPJDQUeoIf5RLt9QFGecJZVmWN2dubn45SWM4MThB4UWz6QR+txYCDyNWIR7drNBzilRk4jiRlv8JVqcv6buP4/jSC5yC1ZPHEJU6M=,iv:jdrNOxN2raRIS7wSXXBBE1bFhn5vCUSgqP5aso/cQCs=,tag:eWLVZCOMUupvbtwqNtggGA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
