apiVersion: ENC[AES256_GCM,data:UoM=,iv:oA+n+eUOvXOhxFVVxpgNeq/Bn9eUokU7m9dYXmmMCIY=,tag:skUgvH57M0FwBx7nN4lQ/Q==,type:str]
kind: ENC[AES256_GCM,data:1QGySk+N,iv:vk90onR9ndK3B1piok0Ss3R2y4HUcOD15ZQPIRc6rSw=,tag:xVYNNOnkqBKuzcRtJqFElQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Q+yZkM58cXVlrFDCI3ERTQ==,iv:XxxPTdBWP6NAhD+QK1vjGREybJqExcgkgIMC+rkqASQ=,tag:yZFHq1eYO3CjhbbHeGhS8A==,type:str]
    namespace: ENC[AES256_GCM,data:U252MyDy2j9L2nU/,iv:csw+7qAnDZtDlXdWSNgJDH9cDURJeNLwW05mCqKtF8Q=,tag:+VJJBZKUft0n0S3r9mc0sw==,type:str]
stringData:
    token: ENC[AES256_GCM,data:q3+mHYf5i13itcocXWJuEen6TAiiDGbK2eNAXMA5U+LCePZtlSu5Qg==,iv:IBGpPm5IT6JS4KyINJHWcL6oIF2DdkquH4xK5e2h678=,tag:m7kUYEmCT0cbuQSyVOsNjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jmtzxhr8gr37jt4uw9h49v6m5wtyxv56lev5rvju0knuvfk57e5sfwdm77
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdW9YSThqQWFnMFU0bGVQ
            MUNLNWI5cHd0N0JIYUloUkxPeWtkeFJvTVNnCnozazdhV0dUeGJQYWRzV1djN0tu
            WXdlRm1nYlZsVTQydEF6bWcvMlF1L0UKLS0tIEtmNXN2N28xTHlCV3U1K3pBOEVX
            aGJyYmFQaGUyZ2Z3ZHdHOFo3d3cveGMK9sqEpbvRWmtZCfEs9aYruCuRmmZM9HAS
            jCsrdIfaXMElw10sYbyoxgrsPrC7nVBCwyBpzjhLbKdUXvZfUak7qQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-19T16:03:22Z"
    mac: ENC[AES256_GCM,data:phmkN9WV3P7WmFt3q57Y2NIuFLQ9WlaMcqH8Fv4TQr9XtZUxvDUd4uN8uO92ZdtaTg5K08rB+NZ8H0r2rUH3CBE4acAbxHVnBdYW9uKVkN5te/QTler3537kyOCsr/7+cVNNys3olnT740hkLabjhOqHNjNYL7ln2jdot6Krbbo=,iv:YLbB/cBHxBgZoJPVHpGB8UjggizUaA9PTWtwpTrOKVk=,tag:c8raSgmh4Wl35YNkkzk2hA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
