---
apiVersion: v1
kind: Namespace
metadata:
  name: envoy-gateway-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  interval: 10m0s
  type: oci
  url: oci://docker.io/envoyproxy
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  interval: 10m0s
  targetNamespace: envoy-gateway-system
  chart:
    spec:
      chart: gateway-helm
      sourceRef:
        kind: HelmRepository
        name: envoy-gateway
      version: 1.4.2
  values:
    deployment:
      replicas: 4 # NOTE: match node count to avoid invalid dns entries.
      pod:
        labels:
          test: "true"
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: control-plane
                        operator: In
                        values:
                          - envoy-gateway
                  topologyKey: "kubernetes.io/hostname"
    config:
      envoyGateway:
        extensionApis:
          enableEnvoyPatchPolicy: true
