---
apiVersion: v1
kind: Namespace
metadata:
  name: k8up
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: k8up
  namespace: k8up
spec:
  url: https://k8up-io.github.io/k8up
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8up
  namespace: k8up
spec:
  interval: 1h
  timeout: 10m
  chart:
    spec:
      chart: k8up
      version: "4.10.0"
      sourceRef:
        kind: HelmRepository
        name: k8up
        namespace: k8up
  install:
    createNamespace: false
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    k8up:
      envVars:
        - name: BACKUP_GLOBALS3ENDPOINT
          value: https://7e3a30e1db0d93b8ad84824b2ce25298.r2.cloudflarestorage.com
        - name: BACKUP_GLOBALS3BUCKET
          value: hmlb-backup
        - name: BACKUP_GLOBALACCESSKEYID
          valueFrom:
            secretKeyRef:
              name: backup-credentials
              key: ACCESS_KEY_ID
        - name: BACKUP_GLOBALSECRETACCESSKEY
          valueFrom:
            secretKeyRef:
              name: backup-credentials
              key: SECRET_ACCESS_KEY
        - name: BACKUP_GLOBALREPOPASSWORD
          valueFrom:
            secretKeyRef:
              name: backup-credentials
              key: RESTIC_PASSWORD
