apiVersion: v1
kind: Secret
metadata:
    name: backup-credentials
    namespace: k8up
type: Opaque
stringData:
    RESTIC_PASSWORD: ENC[AES256_GCM,data:TYhCFaNyAnW2iBrrruc7DYbxfno6TO7N0sf0bXbprSw=,iv:k4LZAWX4f3vR++wib8ICDMEhDfwRwJJZ8N2EEemPSeg=,tag:mVNI7ynuf9OV3VM3IEvnaA==,type:str]
    ACCESS_KEY_ID: ENC[AES256_GCM,data:f4/GaR+fgi84PFCXFg5hf1QEOa0TD8VXqnrbaOOo1dk=,iv:Bg0oikhH92Y3TjsnsLZwlbDFiz2HxQC5ojYkz6TwOkg=,tag:L+eCcjXjArWGNr9373lXuA==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:eCuHqM4iOEdKBJP77KQs+bytOqqVA9cZ8EITVe+KJF5xCd0DgofnsyJNrRnyMf2rY/0Vdz26T5M22SUMWF7UfQ==,iv:tsk5cK5YJTy4LuNVTLXyhfQnhesFlP9jq33fZyFjIDw=,tag:xW0hIXWkaKMAt9fBPiHJXA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWHZIME4wNE9oZFoyQ2M1
            bFNlZEhDRlRqZlRvdzZaOTVsbjFEODhCWFUwCnhrV1NGVGFnUEoydGJOY2JCSExk
            NHBiTC90bDBnVXkyZjRINTNPL3dyUHcKLS0tIC80VENkbXF3emlWWDUyNjZhdVJ0
            bDk0OGZmRG5SWE55bnVvZFpJU0YxRE0KhlHj2edrRnp03L8vJVUNN7HiLVohcHKs
            as4V3ireD7ZaCML6GM1FMuRDzsv8cudTxY4Ofw0R+9H5Ur73ijVlVQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jmtzxhr8gr37jt4uw9h49v6m5wtyxv56lev5rvju0knuvfk57e5sfwdm77
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-20T11:37:05Z"
    mac: ENC[AES256_GCM,data:uMXqkjWx2sjWJliABkwb0zq/M63JLIm5p1XmcwYG0fCBbnAKJa8v3xzrI1+GL/oNPbC9dTPHWujKHbB2CJcjIYZfIlzJb+mTl/pXj9LS8SrgVqAFhcaG2aqcqSBfPp+PCzAzBRBeuwWMoK6Jnj8uuVvy4rdpJA2LhH1VpwKwZPE=,iv:Rcr6+o+CpFqwM7h66fvchMjKQPb2vEFWcWMgoxXaUNY=,tag:ORt8fMAdETnSk9ZQbW2w6w==,type:str]
    version: 3.13.3
