apiVersion: v1
kind: Secret
metadata:
  name: operator-oauth
  namespace: tailscale
type: Opaque
data:
  clientId: azVwcnBOMmFlMzIxQ05UUkwK
  clientSecret: dHNrZXktY2xpZW50LWs1cHJwTjJhZTMyMUNOVFJMLTlEanpneW8xYUZSRk5GY01WUnJQRlJ6dzVoN1ZpR2dOQgo=
