apiVersion: v1
kind: Secret
metadata:
  name: operator-oauth
  namespace: tailscale
type: Opaque
data:
  clientId: a2V3dkNmMXBkUjExQ05UUkwK
  clientSecret: dHNrZXktY2xpZW50LWtld3ZDZjFwZFIxMUNOVFJMLUc0Wno4OGFROFJlemhTYVZqY0RMUmVwY2VMNktqMXFvUAo
