---
apiVersion: v1
kind: Namespace
metadata:
  name: redirect
  labels:
    gateway.infra.services/allow-routes: "true"
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-proxy
  namespace: redirect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi-proxy
  template:
    metadata:
      labels:
        app: unifi-proxy
    spec:
      containers:
        - name: nginx
          image: nginx:1.29-perl
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-config
          configMap:
            name: unifi-proxy-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: unifi-proxy-config
  namespace: redirect
data:
  default.conf: |
    server {
        listen 80;

        location / {
            proxy_pass https://192.168.178.1;
            proxy_ssl_verify off;

            # Standard proxy headers
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # WebSocket support
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            # CORS headers (if needed for frontend JS)
            add_header Access-Control-Allow-Origin *;
            add_header Access-Control-Allow-Methods "GET, OPTIONS";
            add_header Access-Control-Allow-Headers *;

            # Streaming and large payloads
            proxy_buffering off;
            proxy_request_buffering off;
            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
            send_timeout 3600s;
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-proxy
  namespace: redirect
spec:
  selector:
    app: unifi-proxy
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: unifi
  namespace: redirect
spec:
  hostnames:
    - unifi.kndlive.com
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: services
      namespace: infra
      sectionName: main
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: unifi-proxy
          port: 80
