---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: observability-release
  namespace: observability
spec:
  interval: 5m
  path: "./homelab/core/observability/release"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: observability-config
  namespace: observability
spec:
  dependsOn:
    - name: observability-release
  interval: 5m
  path: "./homelab/core/observability/config"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
