apiVersion: v1
kind: Secret
metadata:
    name: backup-credentials
    namespace: jellyfin
type: Opaque
stringData:
    RESTIC_PASSWORD: ENC[AES256_GCM,data:SnuHo78UsyKC8zzJID6hwzy7353wNuUQ6g4xNMRneN8=,iv:OF1QH8BIP/7pwOsJOzQeWXWupXPTbxbSLvQp09w3iMc=,tag:rGwzsvFEat/w8VdcO9/MAw==,type:str]
    ACCESS_KEY_ID: ENC[AES256_GCM,data:AktWeTftKn1IKztebrymlcH9U6Th2heQju3OlQaiTKg=,iv:6L+1KRNceg18/ommEwQ4LMqjMnPP42Rg5L5F7kbxLlw=,tag:2VV6IOlkTCikxIgTQNP1nQ==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:2ipttQbMColFaPGYH8E4sJ7IpelFe3rBMCCuQNwDFX0Jq8drDAcpQoWLFwEQM7VpTcJ+sd0cXwxbzDcrJhk8rw==,iv:huPZVNj4xROVJCgfhSrcLureevDFjHkCXz2ZjX9TAbY=,tag:MxquqbfeR2ciFTUYvpV2kg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdWdzWjNvNFUxTGVRd2N6
            ZUdUVlpsZ0IxOHMxNmt6aVdqektZa29ZNXhrCnV1ajE3WFN5STRrSlA2K1lrREU1
            c2Zxd0RxRXU5eGl6bXdLMEtaS3Z1S2sKLS0tIDk4NGI3TzhWVU1LOGNwQjFmSHhJ
            RmlEUlRqbW9OM3V3RTdiVDR3RGV6WXcKAgSw813qeLP3JlA/M0N6JW8T5FQ981FD
            +71CEbl6ziz7sF/NNLLxyLLONIgVG1VRJU+bNrWDOCo9fLN4zbpthA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jmtzxhr8gr37jt4uw9h49v6m5wtyxv56lev5rvju0knuvfk57e5sfwdm77
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T18:46:04Z"
    mac: ENC[AES256_GCM,data:F0mUcUvr39/MgmFsjKxvZKjKJ9RW9Bk+gipgeBRXrZ5dLLQNUp04oQ7IpV7YK9ggBA7nEkgeqK0EaPQu1dipVHAoMqaHDXAVox3FRMlVVQ/kdszIMMNNG6oKCDJFvTF+PZj2a26ZfD2c6er/LPIC5JQ17hojyci9AIqkPdiabec=,iv:DhRZXEEqX1UWVjEI0rCGq/D1tH7qmrwthbOp4e7K2kw=,tag:oqIVuXXgpSbGVPf2YttlRw==,type:str]
    version: 3.13.3
