apiVersion: ENC[AES256_GCM,data:eo4=,iv:r9k/NSPLDPxIrQoquDlyyMIwnve2TU2BmC8lN07viX8=,tag:cHLT9B5524PdfQCsE4g7bQ==,type:str]
kind: ENC[AES256_GCM,data:kv7ciw7p,iv:qcb+1at3EP46z9xCNZdZwc75lhsUH+rQJw4+gCsj4PM=,tag:oLljVlfS+XSLfmvQI7Whnw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:07NmDnN6s/xqsPG8Lv/GEErEMg5bXl+Ilw==,iv:zHg1a/tIEd9Eox73KxyJ3zhLlM+eCKeIpuKsz/iQmRc=,tag:2Ugb5XwDHot6GBGJpCwrcg==,type:str]
    namespace: ENC[AES256_GCM,data:4JjdrgqqwqQ=,iv:QqBFo07ti3HYsZpYmYw6StZuaepNXLev/tCkH4oyiTI=,tag:h2bPjii0R+qo/olqDoLThQ==,type:str]
type: ENC[AES256_GCM,data:JlBUYDO1,iv:WrqW9ehQuSn+a+OAA8dsJUVLxoyLCFht05dNPjMylM8=,tag:ewWg0VubabH2gsIc7ky5ow==,type:str]
stringData:
    SERVER1_NAME: ENC[AES256_GCM,data:rG3SJKGSdSyq,iv:RC/eQX1UZT/DSwSS3BXrHHKrb2kxf4emfbGx9pFhsy8=,tag:uUuQV9flb6pvGD5P41OU6Q==,type:str]
    SERVER1_HOST: ENC[AES256_GCM,data:ehVprGHsUOoy6HOIsM4+7KJy3x5A5M4=,iv:/rdZQaWJdE40ppZ+pjDWuUzz5iK6DcWj1GK0C1qvp9A=,tag:NHo3SPj5ZXFZ8C+cqtV40A==,type:str]
    SERVER1_USERNAME: ENC[AES256_GCM,data:TZbMeJpo,iv:NlM1ta42RYieLlTJy5uPun3rGkXNgVVTeO+adqltiug=,tag:bSN3hiAntxeKlV6UHQHLSw==,type:str]
    SERVER1_PASSWORD: ENC[AES256_GCM,data:hGXBUYa7YlMtGC3ujMQ=,iv:mAIXzEAnOVGe2ZTkGJUmofdiErreKY11+yt5kYOxJYs=,tag:hBXZKTUtW+5BwSuTNWaGbg==,type:str]
    SERVER2_NAME: ENC[AES256_GCM,data:qfTc,iv:aSgVUMGB0ZcY0W3cYuR7gNPT2SBGWeT8oHvHyW5N0AE=,tag:4CbTPEc7SBr9E/udY8kqng==,type:str]
    SERVER2_HOST: ENC[AES256_GCM,data:PYp53j50MWXnnpKze0/lfaQDMpYZ,iv:pgynbhsMb1Z2CHyASth7ZHkS3WWkMQE1XiCMmI0Z8eQ=,tag:hTBsd2LbX81FcsJzFRbKtw==,type:str]
    SERVER2_USERNAME: ENC[AES256_GCM,data:X+0VvY8U,iv:a2RjApe41mmkECzNFwdJKcOIl+Q3zAQiljO8qt/sDsY=,tag:fTuAoxrhoLJ91peuwSDWfQ==,type:str]
    SERVER2_PASSWORD: ENC[AES256_GCM,data:Mqokq2GbBmBgyZ69QNk=,iv:lA3g4c1yj0SkQA1lW03ZuLIZ/klgXKXEp8gx/7iDYNc=,tag:6USMR0H5SKFwO+iIVVBmuQ==,type:str]
    FEED1_NAME: ENC[AES256_GCM,data:BweZTF9VtBBg,iv:UCuQvkFKKOlur5N18CuudCAxqLUMLCVudYV+HqFP6V0=,tag:nwRB4oqMe3I/ZsMOmw61Cg==,type:str]
    FEED1_URL: ENC[AES256_GCM,data:wiZQLb8Gusa30PfOKswBatzFb/cWGpI/KeF7RcSuFmSdDtNna6e1lcJ/a8U2xqjDR0cfO6VCRr+aTQtRgH3QDqdwQ/jzs3Ss3p6j3EWmw1UMVVt3,iv:GFpDSZtvZAuh1ArYgx7g5co6dlOzF8TcZzN8rRi50Ik=,tag:uPjN7vz/NFSJh0rxEWt9Dw==,type:str]
    FEED2_NAME: ENC[AES256_GCM,data:mOXo0T3Eyg==,iv:vCF79tWWc2fSao902HxX0dhrZfjAEPv66mKXI1y8rek=,tag:CIZJZVJE43dd8ZsDtqe4cg==,type:str]
    FEED2_URL: ENC[AES256_GCM,data:RUqB9mEjyReW7Tyeu/YFl2RPZKHK+TfRftMIe1n9EQTbFS4jBlsdr7JvlTIbeIUNUiHpvf9/jnSoJE2JlW6qSPiXoxel6h4RIKarqBJVAousv0ooRd57/Ao=,iv:+A1jny0CjSxhsyxz1dWwkbu5IqcFL1PjRyG5BzDBr8E=,tag:spc3b8D9K4PDtKCgz8vx7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jmtzxhr8gr37jt4uw9h49v6m5wtyxv56lev5rvju0knuvfk57e5sfwdm77
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhc3VUUkRmMHlkRVhVQlR1
            cENOdU1uRnFlMi82eGtBd0k1eWF4bnpPSkRVCkE3YUlRN1c4MmdIcTZobmI4dk1r
            ZG03Q1pFMEZVbkZyUmUzQlBzYkl0Q3MKLS0tIGZ5L3NBYVR3MkErYW51ME5EUVRQ
            amFYMmdLaWNTUTlFc3pudjJhK2xTbFUKOKA23tcmLb8BIer+Q3fYLNgVwu4HpYaC
            LiyMqzFalXQP4Gsi+AziHNpaBfSmHDiodNDgry4fpLpHj19sV5WEpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-07T00:05:16Z"
    mac: ENC[AES256_GCM,data:jqpwzOdNtGSkPCXgoETwRbIeACfazh1xidTAyLpMzA7doprR5/jSpoUjZa6eukJoH8SGT9Mu38Wt6/hPhchCuCCUw4BUtpY8rj5ZeiGVqmdhkROT3wFxE6Ir++F0bGvzhrV4ezGHvRM57Y5bJFzgLz5jCXin7MCD4wPib8EezhU=,iv:l4OasoOogr2e04KOVzLxLVZOmdvOnAnqJ1e0VqQi47s=,tag:/pkA1WIDk4LDpdPGRUHNgw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
