apiVersion: ENC[AES256_GCM,data:SUk=,iv:uoIBE5/a5LyOK275Q5Z/xsZ0U54MhLwOy9wefXqTzD0=,tag:xOpQN+v6/RG3uKIWiSiGvg==,type:str]
kind: ENC[AES256_GCM,data:FxATCwKF,iv:x+Y4WxA3FZoMt/Lt9vkmlV9Rn0k3tuuQYE6qPFX40W4=,tag:ulveibc4oVbKcRMu9Sr0ow==,type:str]
metadata:
    name: ENC[AES256_GCM,data:BTvzAy63Of5RyW/yOnvqY/EmgH8y3HUg3Q==,iv:DOfCB0RKZeLn6SHIY3efpvahBxLwfdHHTPl1kwuRBIY=,tag:IL2tpnITTtwFurOG+SVVSw==,type:str]
    namespace: ENC[AES256_GCM,data:ExjXK9x0zig=,iv:15nBlqGHZb2ky91Jilt4DCw64zqlAwWZHbdsV8U/cTQ=,tag:N/rmfSTiiGu2pFqis3jrBg==,type:str]
type: ENC[AES256_GCM,data:AtvmhQbC,iv:haGOeI6OAu3O4T3iIWWYQ1zVxGseFtDm6+MVe6Clq2k=,tag:ifbMyZBGm2RanAl3qnZwkA==,type:str]
stringData:
    SERVER1_NAME: ENC[AES256_GCM,data:rTt9IM+D/j0r,iv:zLvd8lQYlAuTprb5IDxPPNTKTbhI+9H8hIQVQtcEWqY=,tag:YRd2+bv5TN6vKvoQnurNMQ==,type:str]
    SERVER1_HOST: ENC[AES256_GCM,data:mpBxPRXn9uvsDCnWag1rnPApkYAfu14=,iv:ftIanlsn8jx33ebLbbd2/9uHQaK1E66x67gbz8jsDM0=,tag:6VZTK6BkbQ5Mda0/CLxzhg==,type:str]
    SERVER1_USERNAME: ENC[AES256_GCM,data:CnyQav0+,iv:nSwApE6GIRMwRvA3pa50jeUw05uTMKQdIgnShOfrbVI=,tag:uCrcXoxvCRnsocPwstGyjA==,type:str]
    SERVER1_PASSWORD: ENC[AES256_GCM,data:BIms75yeFdhnOsgesYQ=,iv:7+7AC/to0fwxuUNWVHf9IdILyqcI2lQb6/HKQG4tYME=,tag:vCCvrn912Not73g/4/6SBg==,type:str]
    SERVER2_NAME: ENC[AES256_GCM,data:uIpM,iv:u+B2yHEpptcaHzqnFlJJXSMGPWkTWO0ftxyIe9rfh8A=,tag:VOkGBMz8Bfb09F/RXCooQQ==,type:str]
    SERVER2_HOST: ENC[AES256_GCM,data:mKJ1OQFLloHOiEcdUkdZ2Wf3s5tL,iv:LoKtfyJaoBmhrMLf7vqVELez24nz3OwFMVTGvKFtKnI=,tag:NrLWy4SKC6vWpSlmMlE1Uw==,type:str]
    SERVER2_USERNAME: ENC[AES256_GCM,data:85xETPVj,iv:d4Do0oP5ru0B2Xp6sqlexcMcTs11tVrNntsawUwbEXg=,tag:4yhwVkMzDKkVlXxiezxuBA==,type:str]
    SERVER2_PASSWORD: ENC[AES256_GCM,data:kNtn7+w/GokKlHNZhqI=,iv:7AII491iq8Kfi4SzZmIg4x9gJBGudzHypRyylQI6v4U=,tag:vv3HYs3rUYerEdZosBX3Gw==,type:str]
    SERVER3_NAME: ENC[AES256_GCM,data:2CHYVAY=,iv:5Gz3mhWsrBTlUHCjcuSXUqjrOhTnd3rE2lwISp9Z3DY=,tag:4OQVea8dmn2JiFXHF7EqDQ==,type:str]
    SERVER3_HOST: ENC[AES256_GCM,data:oMhM1lNDs6a17eELzg==,iv:2afp/0LSi2AkGGCKEvY80mjgBCsMDJM42pV8HoA8YD0=,tag:GMFoFSHfXGFDiMnj+Ouhvg==,type:str]
    SERVER3_USERNAME: ENC[AES256_GCM,data:A7E8GVe89ASR5M7UIjeV0w==,iv:fTmTrIUjgZvrZc2jXLCmt6ss0sLP69DfyZBv6fUuEQY=,tag:SNpEriA8UnBRgWLFIUORig==,type:str]
    SERVER3_PASSWORD: ENC[AES256_GCM,data:+lHYgHrqlRbV/IGSBvM1WpQLtsTMURJELYNxTL9gICHFeYTq,iv:EP+NI7krLp9kiGfqSLLT9Xka8KrCJti/faX0RhbGseY=,tag:2aUOBCRjji3tP4AdAjVYVw==,type:str]
    FEED1_NAME: ENC[AES256_GCM,data:7rynPkhaWw==,iv:K74U1S6emty1cD+d/IYiylnUORiESogXJGoY77OfSME=,tag:3nvdEOhZ1dAqUaVtv7slVQ==,type:str]
    FEED1_URL: ENC[AES256_GCM,data:BEIGvuRIlBfcSM2zetu4+RUzuNTJ4n+m6KGLyiMBRv03BD7SNdsp2osjnYxfUISP++UQnRAgGSFwbnLdOyhPNB8EHT+Q5w3040+b/OstluMI95HBCxPg95M=,iv:WZTDxwLDFhrvdyBhDA5gF8oGBlfOVhh0LqWDrqJgQ0Q=,tag:IZRwe33l6KUoJBKYSF723Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jmtzxhr8gr37jt4uw9h49v6m5wtyxv56lev5rvju0knuvfk57e5sfwdm77
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ZDVOV2YwOE5odkI3MWVI
            SUI0N1F0M3NTYTAyTE40ZGxlSkhoNk0zWGtBCmlpOHJEN1RUK1o2VXphd2RyTHhS
            OWhuWHIvVDhjOWs3RUVBeldkZVFEU2MKLS0tIEFiRXFkNDRWUmVFWUxobVQzQkRq
            MGRPOTlaYlJPRzZnZUdSUEI0V1FSMGsK4OWwVWjjzTos8uyettuy3jlyT8MSgH88
            YTXtq9fvmT1BIQOIfM0JO4kZcUdwLKQa43LyjCfmGuU6CrMEZf1KLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-27T12:24:58Z"
    mac: ENC[AES256_GCM,data:cRpKVGzHKcTnacVQo23BheV4Wh3M1rM/TBLLmZ7GHbHByFMqR31tBlnz+rHbrwqPJWRYvv5Qslk2jl2AaGBbO7lj884ESWD/UEtVaShUcOC1F0PVOi7JAWnQangbRdihEPH4I13FqErJvmcert2m7ubxi55hWqKFreJ34i0DEPg=,iv:+OdOEO4GqQ8z/8llvgmbTpp4h8sXGCQMwoRLcuiW+uU=,tag:7QCfxlCJhewwT+W99MZlPw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
