apiVersion: ENC[AES256_GCM,data:izI=,iv:vro5s4RPAoKg6fVnyXznx97b/g2iumTvZEiJaeNi6sc=,tag:GkIUQW9bRTZYF2/gZbZ0Zw==,type:str]
kind: ENC[AES256_GCM,data:+3aF1vtL,iv:pu9J8ec0i+G8f4cJxWbyszzLk8h4zKuWeE6ThvH5LQc=,tag:9d8xSP2KBPl87AFgQty1pw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:AoX9sYXPOYxiKI/8xQ4uVCY8dCE+pYqp1g==,iv:Rxii9epcLfDsUkRWNstPpcxHRRY+avYaP7tz7Z8y5c8=,tag:+OIaB+le+JzwfNBIJQJCyw==,type:str]
    namespace: ENC[AES256_GCM,data:rJxnzLVCD9o=,iv:DvYaJTDUF7fyZOF9Ue6Sa42kx3/pITkacEiw5yT168g=,tag:fUQiamCji60dOlHccDLYwA==,type:str]
type: ENC[AES256_GCM,data:s6xZybmf,iv:DvD6wJiK75uh6PNOhfH2IFrPI/wsBdoqpfwj/UgefAI=,tag:n/riaos0N6eRHRGUWqOXiw==,type:str]
stringData:
    SERVER1_NAME: ENC[AES256_GCM,data:nlHvYMSiJt8z,iv:KSko3l+JRLwrh7Cku1oWRvlxrhtzX4olaVq+ewEf5mA=,tag:BDWwszNVRQQ0M3IETz7ZLA==,type:str]
    SERVER1_HOST: ENC[AES256_GCM,data:Y5csCm9k/NS78O9OnP8PMZYt0oiCRAw=,iv:TFokYxvk1f9EIpp/3lX0JbCjqK8/rAWDKLgDT43LQcg=,tag:kC/sGbrjwS0wzvgjBXFM2Q==,type:str]
    SERVER1_USERNAME: ENC[AES256_GCM,data:Xgt2VPTv,iv:rQjxRGTNnVmrcXwzK+h3F1QzojCbV7rBtZRdik7/v2Q=,tag:jpszSXF1VzeZcoFHhPSz6g==,type:str]
    SERVER1_PASSWORD: ENC[AES256_GCM,data:KGPGA2cgRS94NvOQ3UY=,iv:sGH3pt/iGGjMR0TzkCei0PaMED7oAfLmYyc29rTInX4=,tag:/VbQyXKDmGe3McepGoO2LQ==,type:str]
    SERVER2_NAME: ENC[AES256_GCM,data:QmJ+,iv:Oh5Hh/cOX+tdLFSbsuzGeoKHpDlPV9qjXp8ia/GyP/U=,tag:3be3Sv3HnwEXsw7zzu2a2Q==,type:str]
    SERVER2_HOST: ENC[AES256_GCM,data:odUFVn5oMex04PBFYPPIGvsjH6Uy,iv:e1CdmSPCrshQhSVVQ3k037uy6v8UtS9JKgsiqeMIkqU=,tag:tLivv+836AzcHV1P7oZcVg==,type:str]
    SERVER2_USERNAME: ENC[AES256_GCM,data:xTTrEZKL,iv:r9lfzQJX0RXA6MLz503r60XpQQhKQvwjxOf959zIjxE=,tag:caSJjSlu0KgOND96FMQpeg==,type:str]
    SERVER2_PASSWORD: ENC[AES256_GCM,data:BPbYE7sWs+jktxySNB4=,iv:N1N+vRGPOrqtgwN4fyQ1v7VkySLE7DCe1H7Q2Ca4kRg=,tag:Xc3ZBY/eG3BXzxJ9+rBXJw==,type:str]
    FEED1_NAME: ENC[AES256_GCM,data:LLtpYjI/7w==,iv:OSdzRWa5TvpOxfbgovwUXOJSqjvPcP8O1GNzpKd22Xc=,tag:jdk7irQ1Rdvbf0JHVD7pkw==,type:str]
    FEED1_URL: ENC[AES256_GCM,data:HQ5paYIK8ozFGA8hgONvzlWnZ5DNkHSFEXkyXN79NhzubkwzfTmEzUkME0r1KEfrOTJbSFhylAp8WL7OFWhqQHszSPAD8JyJvKpZR0m2TH/g1Ho14FqM3T8=,iv:+USdD6kNOHlUTPxTDrK09ghYJyl4E6lkFEWGpAchLLg=,tag:GJ0P7rtZRwhDjBR4KFestw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jmtzxhr8gr37jt4uw9h49v6m5wtyxv56lev5rvju0knuvfk57e5sfwdm77
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudHQxbmwxMXpLQ2Z3Nlgv
            MzRPOHVWWEhML2xmYjhhV3ZPNGFOQkIzV2xVCnQ5N3R5UU80ME9xOGZVWVNOdmZh
            anJLZWRnYkRTNTArU0tRR0JjejRSVWcKLS0tIG9ZMzZiQWZxZWFyZWVRZS9qUi8z
            OFo3VHJxM05DNmFQSFBTRTVNNC93S3cKwGv/XTl0FcVxWqGj+RnPdg1bCTXVGlRZ
            qmUD9P8TvQRMO8/OjLJYzEmD4NUqzske2ontpBMIhi8vlUX979Mzwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-06T12:43:39Z"
    mac: ENC[AES256_GCM,data:1GRkquch7iEiYj93U45VRyFxcBaOR+mjklNa2r+q95f8QwsUH4emHEi1+N1WdmMjGSoTVxGXv9txh/7gXPwxt8RIm1bM9QeVWwMytvlZGabaYrKNTg3MNL4YKUDzznPKh2F+Q/ooRRtXHPlN4dNTV5LwvDap7IRJLYielyuL1tw=,iv:g76EMXEoFR0H+4JdrB2PUWH975S0IPAzYNOE7BbH9mI=,tag:JhKzNg5gQ8N6CrAOYXRxqw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
