---
apiVersion: v1
kind: Namespace
metadata:
  name: jellyfin
  labels:
    gateway.infra.services/allow-routes: "true"
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jellyfin-config
  namespace: jellyfin
spec:
  dependsOn:
    - name: observability-release
      namespace: observability
  interval: 5m
  path: "./homelab/apps/jellyfin/config"
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-repo
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
